config/routes.rb
Change::Application.routes.draw do

  get 'highscores', to: 'scores#highscores'
  post 'score', to: 'scores#add_score', as: 'add_score'

  get '*path', to: 'application#root'
  root to: 'application#root'
end

app/models/score.rb
class Score < ActiveRecord::Base

  scope :highest, -> { order(score: :desc).limit(10) }
  scope :best, -> { highest.first }

  def index_of
    results = Score.find_by_sql(['select * from (select *, row_number() over (order by score desc) as rnum from scores order by score desc) as p1 where id = ?;', id])
    results.first.rnum
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def root

  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def add_score
    score_model = Score.create(score_params)
    render json: serialize_result(score_model)
  end

  def highscores
    @scores = Score.highest
  end

  private

  def score_params
    params.require(:score).permit(:identifier, :score)
  end

  def serialize_result(score_model)
    {
        your:{
            score: score_model.score,
            index: score_model.index_of
        },
        best:{
            score: Score.best.score
        }
    }
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
  SALT = 'mmm...salty'
  def identicon(id)
    md5 = Digest::MD5.hexdigest(id.to_s)
    image_tag "http://vanillicon.com/#{md5}.png"
  end
end

app/views/application/root.html.haml
#game
.no-mobile
.safari-mavericks
  .msg
    %h1
      You seem to be running
      %br
      Safari on Mavericks
    %p
      We're extremely sorry, but we have some draw issues with Safari 7.0 on OSX Mavericks.
    %p
      Please try the game on
      = link_to 'Chrome', 'http://www.google.com/chrome', target: :_blank
      %span or
      = link_to 'Firefox', 'http://www.mozilla.org/en-US/firefox/new/', target: :_blank
      for the full experience.
    %p.dismiss-p
      %a.dismiss{:href => 'javascript:;'}
        Dismiss

= javascript_include_tag :application

app/views/layouts/_footer.html.haml
%footer
  %p.less-space
    Game created by
    = link_to 'Rothschild Games', 'https://github.com/RothschildGames/', target: :_blank
    = '-'
    = link_to '@shayhdavidson', 'https://twitter.com/shayhdavidson', target: :_blank
    &
    = link_to '@yonbergman', 'https://twitter.com/yonbergman', target: :_blank
  %p
    for the
    = link_to 'GitHub Game Off 2013', 'https://github.com/blog/1674-github-game-off-ii', target: :_blank
    •
    view the source on
    = link_to 'GitHub', 'https://github.com/RothschildGames/change', target: :_blank
  %p.less-space
    %span{:class => "browser-compatibility"}= 'Works on'
    = link_to 'Chrome', 'http://www.google.com/chrome', target: :_blank
    %span or
    = link_to 'Firefox', 'http://www.mozilla.org/en-US/firefox/new/', target: :_blank
  %p
    %span ( and non-Mavericks
    = link_to 'Safari', 'http://www.apple.com/safari/', target: :_blank
    %span )
  %p
    %span Check out the
    = link_to 'High Score Table', highscores_path , target: :_blank
  .mixpanel
    = link_to 'https://mixpanel.com/f/partner' do
      = image_tag '//cdn.mxpnl.com/site_media/images/partner/badge_blue.png', alt: 'Mobile Analytics'

app/views/layouts/application.html.haml
!!! 5
%html{:lang => 'en'}
  %head
    %meta{:charset => 'utf-8'}
    %title= t('site.title')
    %meta{:name => 'description', :content => t('site.description')}
    %meta{'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1'}

    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    %link{:href => '/favicon.ico', :rel => 'shortcut icon'}
    %meta{:property => 'og:url', :content => root_url}
    %meta{:property => 'og:title', :content => t('site.title')}
    %meta{:property => 'og:description', :content => t('site.facebook_description')}
    %meta{:property => 'og:image', :content => image_url('facebook.png')}

    = stylesheet_link_tag :application, media: :all
    = csrf_meta_tags
    = render 'layouts/mixpanel'

  %body
    = yield
    = render 'layouts/uservoice'
    = render 'layouts/footer'

app/views/scores/highscores.html.haml
.container.receipt
  %h1 High Score Table
  %table
    - @scores.each_with_index do |score, idx|
      %tr
        %td= "#{idx + 1 })"
        %td= identicon(score.identifier)
        %td= score.score
        %td= score.created_at.to_formatted_s(:short)